la-mia-pizzeria-static/Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        private ICustomLogger _logger { get; set; }
        public PizzaController(ICustomLogger logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            _logger.WriteLog("Index page");
            using (PizzaContext pz = new PizzaContext()) {
                List<Pizza> list = pz.Pizzas.ToList();
                if (list == null)
                    return View("ErrorList");

                return View(list);
            }

        }
        public IActionResult Details(int id)
        {
            using (PizzaContext pz = new PizzaContext())
            {
                Pizza pizza = pz.Pizzas.Where(p => p.Id == id).Include(p => p.Category).Include(p => p.Ingredients).FirstOrDefault();
                return View(pizza);
            }
        }

        public IActionResult Create()
        {
            using(PizzaContext pz = new PizzaContext())
            {
                var ingredients = pz.Ingredients.ToList();

                PizzaFormModel model = new PizzaFormModel();
                List<SelectListItem> listIngredients = new List<SelectListItem>();
                foreach(Ingredient ing in ingredients)
                {
                    listIngredients.Add(new SelectListItem() { Text = ing.Name,Value = ing.Id.ToString()});
                }
                var categories = pz.Categories.ToList();
                model.Categories = categories;
                model.Pizza = new Pizza();
                model.Ingredients = listIngredients;
                return View(model);
            }
           

        }
        [HttpPost]
        public IActionResult Create(PizzaFormModel data)
        {

            if(!ModelState.IsValid)
            {
                using (PizzaContext pz = new PizzaContext())
                {
                    var ingredients = pz.Ingredients.ToList();
                    List<SelectListItem> listIngredients = new List<SelectListItem>();
                    foreach(Ingredient ing in ingredients)
                    {
                        listIngredients.Add(new SelectListItem() { Text = ing.Name, Value = ing.Id.ToString()});
                    }
                    var categories = pz.Categories.ToList();
                    data.Categories = categories;
                    data.Ingredients = listIngredients;
                    return View("Create", data);
                }
                    
            }
            using (PizzaContext context = new PizzaContext())
            {
               
                Pizza pz = new Pizza { Name = data.Pizza.Name, Description = data.Pizza.Description, Image = data.Pizza.Image, Price = data.Pizza.Price, CategoryId = data.Pizza.CategoryId };
                pz.Ingredients = new List<Ingredient>();
                foreach(var ingredientid in data.SelectedIngredients)
                {
                    int intidIngredient = int.Parse(ingredientid);
                    Ingredient ing = context.Ingredients.Where(i => i.Id == intidIngredient).FirstOrDefault();
                    pz.Ingredients.Add(ing);
                }
                context.Pizzas.Add(pz);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

        }
        public IActionResult Edit(int id)
        {
            using(PizzaContext ctx = new PizzaContext())
            {
                Pizza pizza = ctx.Pizzas.Where(p => p.Id == id).Include(p => p.Ingredients).First();
                var categories = ctx.Categories.ToList();
                var ingredients = ctx.Ingredients.ToList();
                List<SelectListItem> listIngredients = new List<SelectListItem>();
                foreach(Ingredient ing in ingredients)
                {
                    listIngredients.Add(new SelectListItem() { Text = ing.Name, Value = ing.Id.ToString(), Selected = pizza.Ingredients.Any(p => p.Id == ing.Id) });
                }
                PizzaFormModel form = new PizzaFormModel();
                form.Pizza = pizza;
                form.Categories = categories;
                form.Ingredients = listIngredients;
                

            return View(form);
            }
       

        }

        [HttpPost]
        public IActionResult Edit(int id,PizzaFormModel data)
        {
            using (PizzaContext ctx = new PizzaContext())
            {
               if(!ModelState.IsValid)
                {
                    var categories = ctx.Categories.ToList();
                    var ingredients = ctx.Ingredients.ToList();
                    List<SelectListItem> listIngredients = new List<SelectListItem>();
                    foreach(var ing in ingredients)
                    {
                        listIngredients.Add(new SelectListItem() { Text = ing.Name, Value = ing.Id.ToString()});
                    }
                    data.Categories = categories;
                    data.Ingredients = listIngredients;
                    return View("Edit",data);
                }
               Pizza pz = ctx.Pizzas.Where(p => p.Id == id).Include(p => p.Ingredients).FirstOrDefault();
                if (pz == null)
                    return NotFound();
                pz.Image = data.Pizza.Image;
                pz.Name = data.Pizza.Name;
                pz.Description = data.Pizza.Description;
                pz.Price =data.Pizza.Price;
                pz.CategoryId = data.Pizza.CategoryId;
                pz.Ingredients.Clear();
                foreach(string idingredient in data.SelectedIngredients)
                {
                    int intidIngredient = int.Parse(idingredient);
                    Ingredient ing = ctx.Ingredients.Where(i => i.Id == intidIngredient).FirstOrDefault();
                    pz.Ingredients.Add(ing);

                }
                
                ctx.Pizzas.Update(pz);
                ctx.SaveChanges();

                return RedirectToAction("index");
            }


        }
        public IActionResult Delete(int id)
        {
            using(PizzaContext ctx = new PizzaContext())
            {
               Pizza pz = ctx.Pizzas.Where(p => p.Id == id).FirstOrDefault();
                if(pz == null)
                    return NotFound();
                ctx.Pizzas.Remove(pz);
                ctx.SaveChanges();
                return RedirectToAction("index");
                


            }
        }


    }
}

la-mia-pizzeria-static/Views/Shared/NewLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_razor_layout</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_razor_layout.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Pizza" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                         <partial name="_LoginPartial" />
                    
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        <footer class="py-3 my-4 foot">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"> <a class="nav-link px-2 text-muted" asp-area="" asp-controller="Pizza" asp-action="Index">Home</a></li>
            <li class="nav-item"> <a class="nav-link px-2 text-muted" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <p class="text-center text-muted">© 2022 Company, Inc</p>
        </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

la-mia-pizzeria-static/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>